/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liftsystem.UI;

public class JPanelBuildingFloor extends javax.swing.JPanel {
    private int floor = 0;
    
    public void setFloor(int floor){
        this.floor = floor;
    }
    
    public int getFloor(){ return floor; }
    
    /**
     * Creates new form JPanelBuildingFloor
     */
    public JPanelBuildingFloor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLift = new javax.swing.JLabel();
        lblNumberOfPeople = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 202, 188), 1, true));
        setOpaque(false);

        lblLift.setBackground(new java.awt.Color(216, 216, 216));
        lblLift.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblLift.setForeground(new java.awt.Color(255, 255, 255));
        lblLift.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLift.setText("Floor: 0");
        lblLift.setToolTipText("");
        lblLift.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 3));
        lblLift.setOpaque(true);

        lblNumberOfPeople.setBackground(new java.awt.Color(102, 102, 102));
        lblNumberOfPeople.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblNumberOfPeople.setForeground(new java.awt.Color(51, 51, 51));
        lblNumberOfPeople.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumberOfPeople.setText("No. Of People: 0");
        lblNumberOfPeople.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLift, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(lblNumberOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblLift, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblNumberOfPeople, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblLift;
    public javax.swing.JLabel lblNumberOfPeople;
    // End of variables declaration//GEN-END:variables
}
